# Comparison between estimate precipitation from IMERG Final Run with ground precipitation data from Automatic Meteorological Stations in Costa Rica

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import ipywidgets as widgets
from IPython.display import display, clear_output
import ipywidgets as widgets

In [2]:
from utils import *

# Short Term Analysis

This section contains the functions and process to plot time series for short term events (duration of few hours).

In [18]:
# Paths for your data files
path1 = './Data/TURR_IMN.csv'
path2 = './Data/TURR_GPM_ST.csv'

In [19]:
df = pd.read_csv(path1, sep=';')

In [20]:
df

              Date  pcp
0    21/7/21 00:00  0.0
1    21/7/21 01:00  0.0
2    21/7/21 02:00  0.0
3    21/7/21 03:00  0.0
4    21/7/21 04:00  0.0
..             ...  ...
115  25/7/21 19:00  0.0
116  25/7/21 20:00  0.0
117  25/7/21 21:00  0.0
118  25/7/21 22:00  0.0
119  25/7/21 23:00  0.0

[120 rows x 2 columns]

In [4]:
# Create a dropdown widget for selecting resolution
resolution_options = ['1H', '3H', '6H', '12H'] 
resolution_dropdown = widgets.Dropdown(
    options=resolution_options,
    value='1H',
    description='Resolution:',
    disabled=False
)

In [5]:
# Create an interactive plot
interactive_plot = widgets.interactive(
    plot_resol,    # plot_resol is a function imported from utils
    path1=widgets.fixed(path1),
    path2=widgets.fixed(path2),
    resolution=resolution_dropdown
)

# Display the interactive plot
display(interactive_plot)

interactive(children=(Dropdown(description='Resolution:', options=('1H', '3H', '6H', '12H'), value='1H'), Outp…

# Long Term Analysis
This section contains the process to plot time series and frecuency sprectrums for long term series (at least 20 years).

In [7]:
# Paths for your data files
path1 = './Data/STCZ_LP_AWS.csv'
path2 = './Data/STCZ_LP_GPM.csv'

In [14]:
df = pd.read_csv(path1, sep=';')

In [15]:
df

        Cuenca  Estaci�n    Fecha      Hora  Lluvia (mm)
0           74        53   1/6/00  00:00:00          0.0
1           74        53   1/6/00     01:00          0.1
2           74        53   1/6/00     02:00          0.0
3           74        53   1/6/00     03:00          0.0
4           74        53   1/6/00     04:00          0.0
...        ...       ...      ...       ...          ...
173419      74        53  14/2/22     05:00          0.0
173420      74        53  14/2/22     06:00          0.0
173421      74        53  14/2/22     07:00          0.0
173422      74        53  14/2/22     08:00          0.0
173423      74        53  14/2/22     09:00          0.0

[173424 rows x 5 columns]

In [9]:
# Create a dropdown widget for selecting resolution
resolution_options = ['1D', '30D', '1Y', '20Y'] 
resolution_dropdown = widgets.Dropdown(
    options=resolution_options,
    value='1D',
    description='Resolution:',
    disabled=False
)

In [10]:
# Create an interactive plot
interactive_plot = widgets.interactive(
    plot_resol,    # plot_resol is a function imported from utils
    path1=widgets.fixed(path1),
    path2=widgets.fixed(path2),
    resolution=resolution_dropdown
)

# Display the interactive plot
display(interactive_plot)

interactive(children=(Dropdown(description='Resolution:', options=('1D', '30D', '1Y', '20Y'), value='1D'), Out…